### ISSUE TITLE
Gives the same color for a lot of strings

### ISSUE THREAD

**Issue by twilight-sparkle-irl** [BelkaLab/material-color-hash#5]
Using a random username from the project I wanted to use this for, and some etc strings I found while just pressing letters, these are all the same color:

* `zoeWhy` 
* `trasn` 
* `fy` 
* `fho`
* `ix`
* `6e`
* `einen`

There's plenty of other strings that all come out to their own same color.

**Comment by GiovanniFrigo** [comment]
This library **does not generate random colors** from strings, but hashes these strings and uses the result to pick a color from the pool of colors provided by material design. 
There are only 19 official colors in material design, so it's normal that some strings will result in the same color being returned.

Unless you are finding a weird distribution (eg, out of 10000 hashes, the red is far more likely to be chosen or something like that), this issue is not valid.

**Comment by GiovanniFrigo** [comment]
If you want to have a little bit more variance, you could also use different shades depending on the hash of the string. In that case the available color combinations would be 19 colors x 10 shades = 190 colors 😃
