### ISSUE TITLE
Gray-scale colors

### ISSUE THREAD

**Issue by amio** [BelkaLab/material-color-hash#6]
Is there a way to prevent gray-scale colors?

For `binance` https://belkalab.github.io/material-color-hash/ gives 10 shades of gray, I wish it could be more colorful 😉

**Comment by GiovanniFrigo** [comment]
Hello amio,

there is currently no way of doing that, since the generation uses the whole palette of the material colors. You could use a hack to achieve that, by appending a space (or any other character really) to the string you are passing in, if the color is gray:

```javascript
function getMaterialColorExcludeGrey(string) {
    let color = toMaterialStyle(string);
    if (color.materialColorName === 'Grey') {
        color = toMaterialStyle(string + ' ');
    }
    return color;
}
```

or maybe even with a while loop, in case you are really unlucky and string + space is still grey ;)

```javascript
function getMaterialColorExcludeGrey(string) {
    let hashString = string;
    let color = toMaterialStyle(hashString);
    while (color.materialColorName === 'Grey') {
        hashString += ' ';
        color = toMaterialStyle(hashString);
    }
    return color;
}
```

that should be sufficient to avoid gray colors in your case.

**Comment by amio** [comment]
Yep, nice workaround @GiovanniFrigo 

Thanks for this awesome package!
